#!/usr/bin/env python3
"""Bundle content/*.md + content/site.json into site/content/guides.js,
and produce artifact/index.html (a body-only copy for claude.ai Artifacts).

Usage:  python3 build.py
Guide files need a front-matter block:
---
id: getting-started
title: Getting Started
category: start
summary: One sentence shown on cards.
tags: beginner, day 1
updated: 2026-09-12
---
Markdown body follows. Files are ordered by filename, so prefix with numbers.
"""
import json, os, re, sys, glob, datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(ROOT, "content")
SITE = os.path.join(ROOT, "site")
OUT = os.path.join(SITE, "content", "guides.js")

def parse(path):
    text = open(path, encoding="utf-8").read()
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", text, re.S)
    if not m:
        sys.exit(f"{path}: missing front matter")
    meta, body = {}, m.group(2).strip() + "\n"
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    for k in ("id", "title", "category", "updated"):
        if k not in meta:
            sys.exit(f"{path}: front matter needs '{k}'")
    g = {
        "id": meta["id"], "title": meta["title"], "category": meta["category"],
        "summary": meta.get("summary", ""), "updated": meta["updated"],
        "tags": [t.strip() for t in meta.get("tags", "").split(",") if t.strip()],
        "body": body,
    }
    if meta.get("copyCodes", "").lower() in ("1", "true", "yes"):
        g["copyCodes"] = True
    return g

def main():
    site = json.load(open(os.path.join(CONTENT, "site.json"), encoding="utf-8"))
    guides = [parse(p) for p in sorted(glob.glob(os.path.join(CONTENT, "*.md")))]
    ids = [g["id"] for g in guides]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        sys.exit(f"duplicate guide ids: {dupes}")
    cats = {c["id"] for c in site["categories"]}
    for g in guides:
        if g["category"] not in cats:
            sys.exit(f"{g['id']}: unknown category '{g['category']}'")
    newest = max(g["updated"] for g in guides) if guides else str(datetime.date.today())
    site.setdefault("site", {})["updated"] = max(newest, site["site"].get("updated", ""))
    codes = {}
    codes_path = os.path.join(SITE, "content", "codes.json")
    if os.path.exists(codes_path):
        try:
            codes = json.load(open(codes_path, encoding="utf-8"))
        except Exception as e:
            print(f"warning: could not read codes.json: {e}")
    data = {"site": site["site"], "categories": site["categories"],
            "notices": site.get("notices", []), "week": site.get("week", []), "codes": codes, "guides": guides}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by build.py — edit content/*.md and content/site.json, then rebuild. */\n")
        f.write("window.KMA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
    print(f"wrote {OUT}: {len(guides)} guides, site updated {data['site']['updated']}")

    # Artifact variant: strip the document wrapper (the Artifact host adds its own).
    html = open(os.path.join(SITE, "index.html"), encoding="utf-8").read()
    head = re.search(r"<head>(.*?)</head>", html, re.S).group(1)
    body = re.search(r"<body>(.*?)</body>", html, re.S).group(1)
    head = re.sub(r"<meta[^>]*>\s*", "", head)  # host supplies charset/viewport
    art = os.path.join(ROOT, "artifact")
    os.makedirs(art, exist_ok=True)
    open(os.path.join(art, "index.html"), "w", encoding="utf-8").write(head.strip() + "\n" + body.strip() + "\n")
    print("wrote artifact/index.html")

if __name__ == "__main__":
    main()
